version: '3.9'
services:
  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: 'db'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db-data:
